const { esc, icon, overline, button, brand } = require('./ui.cjs');
const standards = require('./standards.json');

function header(page){
return '<a class="skip-link" href="#main">Skip to content</a><div class="topbar"><div class="container d-flex justify-content-between gap-3"><span>'+icon('shield')+' Practical guidance. Recognised standards.</span><span class="topbar-right">ISO consultancy across India <span class="topbar-dot">•</span> <a href="contact.html">Let’s talk '+icon('diagonal')+'</a></span></div></div><header class="site-header"><nav class="navbar navbar-expand-lg container" aria-label="Main navigation">'+brand()+'<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainNav" aria-controls="mainNav" aria-expanded="false" aria-label="Open navigation"><span class="navbar-toggler-icon"></span></button><div class="collapse navbar-collapse" id="mainNav"><ul class="navbar-nav mx-auto">'+[['index','Home'],['about','About us'],['services','ISO certifications'],['industries','Industries'],['awards','Awards'],['contact','Contact']].map(([s,t])=>'<li class="nav-item"><a class="nav-link '+(page===s || (page.startsWith('iso-') && s==='services')?'active':'')+'" '+(page===s?'aria-current="page"':'')+' href="'+s+'.html">'+t+'</a></li>').join('')+'</ul>'+button('Get a free consultation','contact.html')+'</div></nav></header>';
}
function footer(c){
return '<footer class="site-footer"><div class="container"><div class="row g-5 footer-main"><div class="col-lg-5">'+brand()+'<p>Practical systems. Confident progress.<br>Your partner in ISO consultancy and<br>certification readiness.</p><span class="footer-signoff">CONSULT. IMPLEMENT. IMPROVE.</span></div><div class="col-6 col-lg-2"><h2>Explore</h2><a href="about.html">About Tricom</a><a href="services.html">Our expertise</a><a href="industries.html">Industries</a><a href="index.html#process">Our process</a><a href="awards.html">Awards &amp; Recognition</a><a href="contact.html">Get in touch</a></div><div class="col-6 col-lg-2"><h2>Certifications</h2>'+standards.map(s=>'<a href="'+s.slug+'.html">'+s.code+'</a>').join('')+'</div><div class="col-lg-3"><h2>Let’s connect</h2><p>'+esc(c.email)+'<br>'+esc(c.phone)+'<br>'+esc(c.city)+'</p><a class="footer-cta" href="contact.html">Start a conversation '+icon('diagonal')+'</a></div></div><div class="footer-bottom"><span>&copy; <span id="year">'+new Date().getFullYear()+'</span> Tricom Consultants. All rights reserved.</span><span>Consultancy with clarity. Progress with purpose.</span></div></div></footer><button class="floating-contact" type="button" data-whatsapp aria-label="Chat about ISO consultancy">'+icon('chat')+'<span>Let’s talk</span></button><button class="back-top" type="button" aria-label="Back to top" hidden>↑</button>';
}
function modals(){
return '<div class="modal fade" id="standardModal" tabindex="-1" aria-labelledby="standard-title" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><span class="eyebrow mb-0">ISO CONSULTANCY</span><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><h2 id="standard-title"></h2><h3 id="standard-name"></h3><p id="standard-description"></p><div class="modal-scope"><h4>How we can help</h4><p id="standard-scope"></p></div><p class="small">Certification is awarded by an independent certification body following its assessment.</p></div><div class="modal-footer"><a id="standard-details" class="btn btn-outline-primary" href="services.html">More details</a><a id="standard-enquire" class="btn btn-primary" href="contact.html">Discuss this standard '+icon('arrow')+'</a></div></div></div></div><div class="modal fade" id="enquiryModal" tabindex="-1" aria-labelledby="enquiry-title" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-4" id="enquiry-title">Your enquiry preview</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><p id="enquiry-status" role="status"></p><pre id="enquiry-preview"></pre></div><div class="modal-footer"><button class="btn btn-outline-primary" id="download-enquiry" type="button">Download enquiry '+icon('document')+'</button><a class="btn btn-primary" id="send-enquiry" hidden>Open email app '+icon('arrow')+'</a></div></div></div></div><div class="modal fade" id="whatsappModal" tabindex="-1" aria-labelledby="whatsapp-title" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h2 class="modal-title fs-4" id="whatsapp-title">Let’s connect</h2><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button></div><div class="modal-body"><p>WhatsApp will be available once the official business number is added. You can explore the enquiry form in the meantime.</p>'+button('Prepare an enquiry','contact.html')+'</div></div></div></div>';
}

module.exports = { header, footer, modals };
